ARG appdir=/srv/openbudgets

FROM ruby:2.5.1-slim

RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
           build-essential \
           curl \
           git \
           gnupg \
           libpq-dev \
    && curl -sL https://deb.nodesource.com/setup_8.x | bash - \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
           nodejs \
    && rm -rf /var/lib/apt/lists/*

ARG appdir
WORKDIR $appdir

COPY Gemfile Gemfile.lock $appdir/
RUN bundle install

COPY package.json package-lock.json $appdir/
RUN npm install --unsafe-perm

ENV HOST=0.0.0.0

CMD ["bash"]
